MVC course code/MvcCourse/Models/BrokenFormModel.cs
namespace MvcCourse.Models
{
    public class BrokenFormModel
    {
        public int ANumber { get; set; }
    }
}

MVC course code/MvcCourse/Models/DocumentationFormModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcCourse.Models
{
    public class DocumentationFormModel
    {
        [Required]
        [AllowHtml]
        public string BodyText { get; set; }

        [Required]
        [MaxLength(200)]
        public string Name { get; set; }

        public IEnumerable<HttpPostedFileBase> Images { get; set; }
    }
}

MVC course code/MvcCourse/Models/DocumentationVersion.cs
using System;
using System.Runtime.Serialization;

namespace MvcCourse.Models
{

    [DataContract(Name = "version")]
    public class DocumentationVersion
    {
        [DataMember(Name = "name")]
        public string Name { get; set; }
        
        [DataMember(Name = "publishDate")]
        public DateTime PublishDate { get; set; }

        [DataMember(Name = "versionId")]
        public Guid VersionId { get; set; }
    }
}

MVC course code/MvcCourse/Models/DocumentationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Web.PublishedContentModels;

namespace MvcCourse.Models
{
    public class DocumentationViewModel : Documentation
    {
        public DocumentationViewModel(IPublishedContent content) : base(content)
        {
        }

        public IEnumerable<LandingPage> LandingPages { get; set; }
    }
}

MVC course code/MvcCourse/Controllers/BrokenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcCourse.Models;
using Umbraco.Web.Mvc;

namespace MvcCourse.Controllers
{
    public class BrokenController : SurfaceController
    {
        // GET: Broken
        public ActionResult Submit(BrokenFormModel model)
        {
            //In cases the model does not validate
            if (ModelState.IsValid == false)
                return CurrentUmbracoPage();

            //this will explode when = 0
            var result = 1000/model.ANumber;

            
            return RedirectToCurrentUmbracoPage();
        }
    }
}

MVC course code/MvcCourse/Controllers/DocumentationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcCourse.Models;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;
using Umbraco.Web.PublishedContentModels;

namespace MvcCourse.Controllers
{
    public class DocumentationController : RenderMvcController
    {
        // GET: DocumentationController
        public ActionResult Index(RenderModel model)
        {
            //get the related landing pages
            var ids = Services.RelationService.GetByParentId(model.Content.Id)
                            .Select(x => x.ChildId);

            //fetch them as nodes
            var products = Umbraco.TypedContent(ids).OfType<LandingPage>();

            // create a new view model
            var viewmodel = new DocumentationViewModel(model.Content)
            {
                LandingPages = products
            };

            return CurrentTemplate(viewmodel);
        }
    }
}

MVC course code/MvcCourse/Controllers/DocumentationFormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcCourse.Helper;
using MvcCourse.Models;
using Umbraco.Core.Services;
using Umbraco.Web.Mvc;
using Umbraco.Web.PublishedContentModels;

namespace MvcCourse.Controllers
{
    public class DocumentationFormController : SurfaceController
    {
        [ChildActionOnly]
        public ActionResult Render(Documentation model)
        {
            var docFormModel = new DocumentationFormModel
            {
                Name = model.Name,
                BodyText = model.BodyText.ToString()
            };
            return PartialView(docFormModel);
        }

        [HttpPost]
        public ActionResult Submit(DocumentationFormModel model)
        {
            if (!ModelState.IsValid)
            {
                return CurrentUmbracoPage();
            }

            var curPageId = CurrentPage.Id;
            var content = Services.ContentService.GetById(curPageId);
            var bodyTextProp = Documentation.GetModelPropertyType(d => d.BodyText);

            content.Name = model.Name;
            content.SetValue(bodyTextProp.PropertyTypeAlias, model.BodyText);

            if (model.Images.HasFiles() && model.Images.ContainsImages())
            {
                var imagesProperty = Documentation.GetModelPropertyType(d => d.Images);
                var folderId = content.GetValue<int>(imagesProperty.PropertyTypeAlias);
                var mediaService = Services.MediaService;

                if (folderId <= 0)
                {
                    var folder = mediaService.CreateMedia(model.Name, -1, Folder.ModelTypeAlias);
                    mediaService.Save(folder);
                    folderId = folder.Id;
                    content.SetValue(imagesProperty.PropertyTypeAlias, folderId);
                }

                foreach (var file in model.Images)
                {
                    if (file.IsImage())

                    {
                        var mediaImage = mediaService.CreateMedia(file.FileName, folderId, Image.ModelTypeAlias);
                        var umbFileProp = Image.GetModelPropertyType(i => i.UmbracoFile);

                        mediaImage.SetValue(umbFileProp.PropertyTypeAlias, file);
                        mediaService.Save(mediaImage);
                    }
                }
            }

            Services.ContentService.SaveAndPublishWithStatus(content);


            return RedirectToCurrentUmbracoPage();
        }
    }
}

MVC course code/MvcCourse/Controllers/DocumentationHistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http;
using MvcCourse.Models;
using Umbraco.Web.WebApi;

namespace MvcCourse.Controllers
{
    public class DocumentationHistoryController : UmbracoApiController
    {
        [HttpGet]
        public IEnumerable<DocumentationVersion> Versions(int id)
        {
            return Services.ContentService.GetVersions(id).Select(x => new DocumentationVersion
            {
                Name = x.Name,
                PublishDate = x.UpdateDate,
                VersionId = x.Version
            });
        }

        [HttpGet]
        public string PublishVersion(Guid version)
        {
            var content = Services.ContentService.GetByVersion(version);
            Services.ContentService.Publish(content);
            var newUrl = Umbraco.Url(content.Id);
            return newUrl;
        }
    }
}

MVC course code/MvcCourse/Views/Broken.cshtml
@using MvcCourse.Models
@inherits UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-9">
            <div class="page-header">
                <h1>@Umbraco.Field("pageName")</h1>
            </div>
            
            @Umbraco.Field("bodyText")


            @Html.Partial("/Views/Partials/brokenform.cshtml", new BrokenFormModel())

        </div>
    </div>
</div>    
    
    

MVC course code/MvcCourse/Views/DocumentationForm/Render old.cshtml
@using MvcCourse.Controllers
@model MvcCourse.Models.DocumentationFormModel
@using (Html.BeginUmbracoForm<DocumentationFormController>("Submit"))
{
    <div>
        @Html.TextBoxFor(m => m.Name)
    </div>
    <div>
        @Html.TextAreaFor(m => m.BodyText)
    </div>

    <input type="submit" value="Submit"/>
}

MVC course code/MvcCourse/Views/DocumentationForm/Render.cshtml
@model MvcCourse.Models.DocumentationFormModel
    @using MvcCourse.Controllers

@using (Html.BeginUmbracoForm<DocumentationFormController>("Submit"))
{
    @Html.ValidationSummary()

    <div class="form-group">
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BodyText)
        @Html.TextAreaFor(model => model.BodyText, new { id = "doc-body-text", rows = 10, @class = "well editable" })
        @Html.ValidationMessageFor(model => model.BodyText)
    </div>

    <div class="form-group">
        <div style="position:relative;">
            <a class='btn btn-primary' href='javascript:;'>
                Choose File...
                <input type="file" style='position:absolute;z-index:2;top:0;left:0;filter: alpha(opacity=0);-ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";opacity:0;background-color:transparent;color:transparent;' name="images" multiple size="40" onchange='$("#upload-file-info").html($(this).val());'>
            </a>
            &nbsp;
            <span class='label label-info' id="upload-file-info"></span>
        </div>
    </div>

    <hr />

    <input type="submit" class="btn btn-default" value="Save" />
}

MVC course code/MvcCourse/Views/Homepage.cshtml
@inherits UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

<!-- promo slider html -->
<div id="myCarousel" class="carousel slide">
	<div class="carousel-inner">
		<div class="item active" style="background-image:url('/images/HQ_9975.jpg');">
			<div class="carousel-caption">
				<h2>Slide 1</h2>
				<h3>A captivating subheading will go here ...</h3>
				<p>Description</p>
				<p><a class="btn btn-info" href="#" role="button">Read More</a></p>
			</div>
		</div>
		<div class="item" style="background-image:url('/images/HQ_9826.jpg');">
			<div class="carousel-caption">
				<h2>Slide 2</h2>
				<h3>A captivating subheading will go here ...</h3>
				<p>Description</p>
				<p><a class="btn btn-info" href="#" role="button">Read More</a></p>
			</div>
		</div>
	</div>

	<a class="carousel-control left" href="#myCarousel" data-slide="prev">
		<span class="icon-prev"></span>
	</a>
	<a class="carousel-control right" href="#myCarousel" data-slide="next">
		<span class="icon-next"></span>
	</a>
</div>
<!-- end promo slider html -->

		
 <div class="container marketing">
	<div class="row">
		<h1>Awesomeness for everyone!</h1>
	    <div class="col-md-6">
	        
	        @Umbraco.Field("bodyText")

			<p><a class="btn btn-info" href="#" role="button">Read More &raquo;</a></p>
	    </div>

		<div class="col-md-6">
			<div class="col-sm-6 block-odd about-blocks" style="background-image:url('/images/HQ_0413.jpg');"></div>
			<div class="col-sm-6 block-even about-blocks" style="background-image:url('/images/HQ_9953.jpg');"></div>
			<div class="col-sm-6 block-odd about-blocks" style="background-image:url('/images/HQ_9986.jpg');"></div>
			<div class="col-sm-6 block-even about-blocks" style="background-image:url('/images/HQ_9921.jpg');"></div>
		</div>
	</div>

	<hr>

	<div class="row bottom-body">
		<h1>What can we help you find?</h1>
		<div class="col-sm-4">
			<p class="glyphicon glyphicon-globe text-center"></p>
			<h3>Knowledge</h3>
			<ul>
				<li><a href="#">The most creative ideas</a></li>
				<li><a href="#">Precise and impartial approach</a></li>
				<li><a href="#">Providing best solutions</a></li>
				<li><a href="#">Individual customer support</a></li>
				<li><a href="#">Fresh ideas for growing your business</a></li>
			</ul>
		</div>
		<div class="col-sm-4 news-items">
			<p class="glyphicon glyphicon-list-alt text-center"></p>
			<h3>Latest News</h3>
			<ul>
				<li><a href="#">Our Big News Headline 1</a><br />6/8/2015</li>
				<li><a href="#">Our Big News Headline 2</a><br />6/8/2015</li>
				<li><a href="#">Our Big News Headline 3</a><br />6/8/2015</li>
				<li><a href="#">Our Big News Headline 4</a><br />6/8/2015</li>
			</ul>
		</div>
		<div class="col-sm-4">
			<p class="glyphicon glyphicon-screenshot text-center"></p>
			<h3>Locations</h3>
			<ul>
				<li><a href="#">Odense, Denmark</a></li>
				<li><a href="#">Bellingham, Washington</a></li>
				<li><a href="#">Sydney, Austrailia</a></li>
				<li><a href="#">New York City, New York</a></li>
				<li><a href="#">Paris, France</a></li>
			</ul>
		</div>
	</div>
</div>

<!-- Footer Area -->
<div class="container social-area">
	<div class="row pre-footer">
		<div class="col-md-6 text-center">
			<h4>Social Media</h4>
			<div class="icons">
				<a href="#" class="facebook"></a>
				<a href="#" class="twitter"></a>
				<a href="#" class="linkedin"></a>
				<a href="#" class="github"></a>
				<a href="" class="rss"></a>
			</div>
		</div>
		<div class="col-md-6 text-center">
			<h4>Contact us</h4>
			<p>Umbraco HQ
				Haubergsvej 1<br />
				DK-5000 Odense C<br />
				+45 70 26 11 62
			</p>
		</div>
	</div>

	<div class="row base-footer">
		<div class="footer-info">
			<p class="pull-right"><a href="#">Back to top</a></p>
			<p>&#169; @(DateTime.Today.Year) Company, Inc. <a href="#">Privacy</a> | <a href="#">Terms</a></p>
		</div>
	</div>
</div>
<!-- End Footer Area -->

MVC course code/MvcCourse/Views/Master.cshtml
@inherits UmbracoTemplatePage
@{
	Layout = null;
}

<!doctype html>
<html>
	<head>
		<title>@Umbraco.Field("pageName")</title>
		<meta charset="utf-8">
		<link rel="stylesheet" href="~/css/socialiconstyle.css" />
		<link rel="stylesheet" href="~/css/bootstrap.min.css" />
		<link rel="stylesheet" href="~/css/carousel.css" />
		<link rel="stylesheet" href="~/css/magnific-popup-lightbox.css" />
		<link rel="stylesheet" href="~/css/umasterclass.css" />

		<script type="text/javascript" src="/scripts/jquery.min.js"></script>
		<script type="text/javascript" src="/scripts/bootstrap.min.js"></script>
		<script type="text/javascript" src="/scripts/magnific-popup-lightbox.js"></script>
		<script type="text/javascript" src="/scripts/website.js"></script>
		
		<link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/5.13.0/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
	    <link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/5.13.0/css/themes/default.min.css" type="text/css" media="screen"  charset="utf-8" />
	</head>
	<body>
		<!-- Nav -->
		<nav class="navbar navbar-inverse">
			<div class="container">
				<a href="/" class="navbar-brand">
					<img alt="Umbraco" src="/images/umbracoblack.png">
				</a>
				<button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<div class="collapse navbar-collapse navHeaderCollapse">
					
					<!-- Navbar -->
					@{ var selection = CurrentPage.Site().Children.Where("Visible"); }

					<ul class="nav navbar-nav">
						@foreach (var item in selection)
						{
							<li class="@(item.IsAncestorOrSelf(CurrentPage) ? "current" : null)">
								<a href="@item.Url">@item.Name</a>
							</li>
						}
					</ul>
						
					<!-- End Navbar -->
							
					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Guest<b class="caret"></b></a>
							<ul class="dropdown-menu">
								<!-- If logged on -->
								<li><a href="/logout"><i class="glyphicon glyphicon-off"></i> Log Out</a></li>
								<!-- else -->
								<li><a href="/login"><i class="glyphicon glyphicon-lock"></i> Log In</a></li>
								<li><a href="/register"><i class="glyphicon glyphicon-pencil"></i> Register</a></li>
							</ul>
						</li>
						<li>
							<form class="navbar-form navbar-right" role="search" action="/search">
								<div class="form-group">
									<input type="text" name="q" class="form-control span2" placeholder="Search">
								</div>
							</form>
						</li>
					</ul>
				</div>
			</div> 
		</nav>
		<!-- End Nav -->
		
		<!-- Child template begins -->
		@RenderBody()
		<!-- Child template ends -->
        
        <script src="//cdn.jsdelivr.net/medium-editor/5.13.0/js/medium-editor.min.js"></script>
        <script>var editor = new MediumEditor('textarea.editable');</script>

	</body>
</html>

MVC course code/MvcCourse/Views/Partials/BrokenForm.cshtml
@using MvcCourse.Controllers
@model MvcCourse.Models.BrokenFormModel

@using (Html.BeginUmbracoForm<BrokenController>("Submit"))
{
    <label>Enter a number</label>
    @Html.TextBoxFor(model => model.ANumber)
    
    <input type="submit" value="Send me a number"/>
}

MVC course code/MvcCourse/Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

MVC course code/MvcCourse/Views/Partials/Grid/Bootstrap3.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

MVC course code/MvcCourse/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

MVC course code/MvcCourse/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates
@Html.Raw(Model.value)

MVC course code/MvcCourse/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

MVC course code/MvcCourse/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }
    
    <img src="@url" alt="@Model.value.altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

MVC course code/MvcCourse/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))

MVC course code/MvcCourse/Views/Partials/Grid/Editors/Textstring.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.editor.config.markup != null)
{
    string markup = Model.editor.config.markup.ToString();

    markup = markup.Replace("#value#", Model.value.ToString());
    markup = markup.Replace("#style#", Model.editor.config.style.ToString());

    <text>
        @Html.Raw(markup)
    </text>
}
else
{
    <text>
        <div style="@Model.editor.config.style">@Model.value</div>
    </text>
}

MVC course code/MvcCourse/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        
        @RenderBody()

        <hr/>
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

MVC course code/MvcCourse/Views/edit.cshtml
@inherits UmbracoTemplatePage<Documentation>
@{
    Layout = "Master.cshtml";
}

<div class="container">
    <div class="row">
        <div class="colmd9">
            <div class="pageheader">
                <h1> Edit: @Umbraco.Field("pageName")</h1>
            </div>
            @Html.Action("Render", "DocumentationForm", new { model = Model.Content })
        </div>
    </div>
</div>

MVC course code/MvcCourse/Views/landingPage.cshtml
@inherits UmbracoTemplatePage
@{
	Layout = "Master.cshtml";
	
	//get the related landing pages
    var ids = UmbracoContext
                    .Application.Services
                    .RelationService.GetByChildId(Model.Content.Id)
                    .Select(x => x.ParentId);
                    
    //fetch them as nodes
    var docs = Umbraco.TypedContent(ids)
                           .Where(x => x.DocumentTypeAlias == "documentation").ToList();
}

<div class="container">
	<div class="row">
		<div class="page-header">
				<h1>@Umbraco.Field("pageName")</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-9">
			@Umbraco.Field("productSpecSheet")
		</div>
				
		<div class="col-md-3">
			@if (docs.Any())
			{
				<ul class="nav nav-list">
					<li><h4>Documentation</h4></li>
					@foreach (var item in docs)
					{
						<li>
							<a href="@item.Url">@item.Name</a>
						</li>
					}
				</ul>
			}
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-12">
			<footer>
				Updated by 
				@Umbraco.Field("writerName")
				on
				@Umbraco.Field("updateDate", formatAsDate: true)
			</footer>
		</div>
	</div>
</div>

MVC course code/MvcCourse/Views/textpage.cshtml
@inherits UmbracoTemplatePage
@{
	Layout = "Master.cshtml";
}

<div class="container">
	<div class="row">
		<div class="col-md-9">
			<div class="page-header">
				<h1>@Umbraco.Field("pageName")</h1>
			</div>

			@Umbraco.Field("bodyText")

		</div>
	</div>
	
	<div class="row">
		<div class="col-md-12">
			<footer>
				Updated by 
				@Umbraco.Field("writerName")
				on
				@Umbraco.Field("updateDate", formatAsDate: true)
			</footer>
		</div>
	</div>
</div>